# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
development:
  adapter: async
  # 開発環境ではローカルメモリ上で完結する async アダプターを利用

test:
  adapter: async
  # テスト環境でも async（または test）を指定し、
  # solid_cable の connects_to 呼び出しを回避

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable_production
  polling_interval: 0.1.seconds
  message_retention: 1.day