default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: deploy_user
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: w_p_a_development

test:
  <<: *default
  database: w_p_a_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cable_production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

queue:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cache:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

