default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: deploy_user
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: w_p_a_development

test:
  <<: *default
  database: w_p_a_test

production:
  <<: *default
  database: w_p_a_production

cable_production:
  <<: *default
  database: w_p_a_production_cable

queue:
  <<: *default
  database: w_p_a_production_queue

cache:
  <<: *default
  database: w_p_a_production_cache  # 新しく追加

